name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # First of every month

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Date
        id: date
        run: |
          echo "title=$(date +'%m.%Y')" >> "$GITHUB_OUTPUT"
          echo "tag=$(date +'%d.%m.%Y')" >> "$GITHUB_OUTPUT"
      - name: Test
        run: |
          echo ${{steps.date.outputs.title}}
          echo ${{steps.date.outputs.tag}}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          name: ${{steps.date.outputs.title}}
          tag_name: ${{steps.date.outputs.tag}}
